export const genres = ['All', 'Nature', 'Lofi', 'Instrumental', 'Ambient', 'Atmospheric', 'Dark', 'Energizing', 'Magnificent', 'Sentimental']

export const themes = {
  light: {
    primary: 'bg-white',
    secondary: 'bg-gray-100',
    text: 'text-gray-900',
    background: 'bg-gray-50',
    pattern: 'circles',
  },
  dark: {
    primary: 'bg-gray-800',
    secondary: 'bg-gray-700',
    text: 'text-white',
    background: 'bg-gray-900',
    pattern: 'waves',
  },
  nature: {
    primary: 'bg-green-600',
    secondary: 'bg-green-200',
    text: 'text-gray-900',
    background: 'bg-green-50',
    pattern: 'leaves',
  },
  ocean: {
    primary: 'bg-blue-500',
    secondary: 'bg-blue-100',
    text: 'text-gray-900',
    background: 'bg-blue-50',
    pattern: 'bubbles',
  },
  'nature-dark': {
    primary: 'bg-green-900',
    secondary: 'bg-green-800',
    text: 'text-green-100',
    background: 'bg-green-950',
    pattern: 'trees',
  },
  'ocean-dark': {
    primary: 'bg-blue-900',
    secondary: 'bg-blue-800',
    text: 'text-blue-100',
    background: 'bg-blue-950',
    pattern: 'waves',
  },
}

export const questions = [
  { id: 1, text: "1. I found it hard to wind down", type: "s" },
  { id: 2, text: "2. I was aware of dryness of my mouth", type: "a" },
  { id: 3, text: "3. I couldn't seem to experience any positive feeling at all", type: "d" },
  { id: 4, text: "4. I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)", type: "a" },
  { id: 5, text: "5. I found it difficult to work up the initiative to do things", type: "d" },
  { id: 6, text: "6. I tended to over-react to situations", type: "s" },
  { id: 7, text: "7. I experienced trembling (e.g. in the hands)", type: "a" },
  { id: 8, text: "8. I felt that I was using a lot of nervous energy", type: "s" },
  { id: 9, text: "9. I was worried about situations in which I might panic and make a fool of myself", type: "a" },
  { id: 10, text: "10. I felt that I had nothing to look forward to", type: "d" },
  { id: 11, text: "11. I found myself getting agitated", type: "s" },
  { id: 12, text: "12. I found it difficult to relax", type: "s" },
  { id: 13, text: "13. I felt down-hearted and blue", type: "d" },
  { id: 14, text: "14. I was intolerant of anything that kept me from getting on with what I was doing", type: "s" },
  { id: 15, text: "15. I felt I was close to panic", type: "a" },
  { id: 16, text: "16. I was unable to become enthusiastic about anything", type: "d" },
  { id: 17, text: "17. I felt I wasn't worth much as a person", type: "d" },
  { id: 18, text: "18. I felt that I was rather touchy", type: "s" },
  { id: 19, text: "19. I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)", type: "a" },
  { id: 20, text: "20. I felt scared without any good reason", type: "a" },
  { id: 21, text: "21. I felt that life was meaningless", type: "d" },
]

export const questionsdesc = [
  { id: 1, text: "It means having trouble relaxing or calming down after a stressful day"},
  { id: 2, text: "It means feeling a dry mouth due to stress or anxiety"},
  { id: 3, text: "It means not being able to feel happy or good about anything."},
  { id: 4, text: "It means having trouble breathing, like feeling short of breath or breathing very fast without physical activity."},
  { id: 5, text: "It means struggling to feel motivated or get started on tasks."},
  { id: 6, text: "It means I often reacted more than necessary."},
  { id: 7, text: "It means I felt my hands or body shake due to stress or anxiety"},
  { id: 8, text: "It means feeling very anxious or tense."},
  { id: 9, text: "It means feeling afraid of losing control and embarrassing yourself in certain situations."},
  { id: 10, text: "It means feeling like there was nothing positive or exciting ahead in life."},
  { id: 11, text: "It means I started to feel upset or anxious."},
  { id: 12, text: "It means I had trouble calming down or feeling at ease."},
  { id: 13, text: "It means I felt sad or discouraged."},
  { id: 14, text: "It means I became upset or frustrated with anything that interrupted or slowed me down."},
  { id: 15, text: "It means I felt like I was about to panic or lose control."},
  { id: 16, text: "It means I couldn't feel excited or interested in anything."},
  { id: 17, text: "It means I felt unimportant or lacked self-worth."},
  { id: 18, text: "It means I felt easily upset or irritated by things."},
  { id: 19, text: "It means I could feel my heart beating quickly or unevenly without doing any physical activity."},
  { id: 20, text: "It means I was afraid even though nothing was wrong."},
  { id: 21, text: "It means I felt like life had no purpose or value."},
]

